import { ToolConfig } from '../types';

export const TOOL_CONFIGS: Record<string, ToolConfig> = {
  claude: {
    id: 'claude-ai-text-watermark-remover',
    name: 'Claude AI Text Watermark Remover',
    provider: 'claude',
    route: '/claude-ai-text-watermark-remover',
    pageTitle: 'Claude AI Text Watermark Remover – Free Claude Text Cleaner',
    metaDescription: 'Analyze, detect invisible characters, and clean Claude-generated text with our free Claude text watermark remover and cleaner.',
    h1: 'Claude AI Text Watermark Remover',
    heroBadge: 'Specialized Anthropic Claude Text Cleaner',
    leadParagraph: 'Analyze and clean Claude-generated text for invisible Unicode characters, formatting artifacts, unusual whitespace, and other detectable text artifacts with 100% client-side privacy.',
    primaryKeywords: [
      'Claude ai text watermark remover',
      'Claude text watermark remover',
    ],
    secondaryKeywords: [
      'Claude watermark remover',
      'Claude AI watermark remover',
      'remove Claude watermark',
      'Claude text cleaner',
      'Claude AI text cleaner',
      'clean Claude text',
    ],
    features: [
      {
        title: 'Invisible Character Detection',
        description: 'Detects zero-width spaces (U+200B), non-joiners (U+200C), joiners (U+200D), and byte order marks in Claude outputs.',
        iconName: 'Layers',
      },
      {
        title: 'Whitespace Normalization',
        description: 'Fixes irregular non-breaking spaces (U+00A0), multiple space clusters, and trailing line returns.',
        iconName: 'FileCode',
      },
      {
        title: 'Multilingual Preservation',
        description: 'Safely protects Arabic, Urdu, Chinese, Japanese, emoji ligatures, and punctuation without corruption.',
        iconName: 'ShieldCheck',
      },
      {
        title: 'Instant Client-Side Cleaning',
        description: 'Your Claude text is analyzed entirely in your browser without uploading to external servers.',
        iconName: 'Sparkles',
      },
    ],
    detectionCapabilities: [
      {
        title: 'Invisible Control Characters',
        items: [
          'Zero Width Space (U+200B)',
          'Zero Width Non-Joiner (U+200C)',
          'Zero Width Joiner (U+200D)',
          'Word Joiner (U+2060)',
          'Byte Order Mark (U+FEFF)',
          'Left-to-Right / Right-to-Left Marks (U+200E, U+200F)',
        ],
      },
      {
        title: 'Whitespace & Formatting Anomalies',
        items: [
          'Non-Breaking Spaces (U+00A0)',
          'En / Em Spaces (U+2002, U+2003)',
          'Thin & Hair Spaces (U+2009, U+200A)',
          'Consecutive space sequences',
          'Inadvertent markdown copy fragments',
        ],
      },
    ],
    faqs: [
      {
        question: 'What is a Claude AI text watermark remover?',
        answer: 'A Claude AI text watermark remover is a specialized utility that scans text generated by Anthropic\'s Claude for invisible Unicode characters, formatting artifacts, non-standard whitespace, and copy-paste remnants. It provides deterministic cleaning to ensure text is clean, readable, and properly formatted.',
      },
      {
        question: 'Can this tool detect invisible characters in Claude text?',
        answer: 'Yes. The tool performs a deep scan across all Unicode code points to detect zero-width spaces (U+200B), zero-width joiners, byte-order marks (BOM), and soft hyphens that frequently enter clipboards when copying from web interfaces.',
      },
      {
        question: 'How does Claude text cleaning work?',
        answer: 'The cleaning engine runs deterministically in your browser. It removes explicitly identified unwanted control characters and normalizes irregular whitespace while preserving all legitimate words, sentences, punctuation, and non-English scripts (such as Arabic, Chinese, and Japanese).',
      },
      {
        question: 'Does this tool guarantee removal of an AI watermark?',
        answer: 'No tool can or should claim guaranteed removal of statistical or probabilistic AI watermarks. We provide honest, deterministic technical cleaning of invisible characters, Unicode anomalies, and formatting artifacts. We do not make false claims regarding AI detector bypass.',
      },
      {
        question: 'Does the tool store my Claude text?',
        answer: 'No. All analysis and deterministic text cleaning take place entirely within your browser client. No text is transmitted or saved to external databases.',
      },
      {
        question: 'Can I clean Claude text for free?',
        answer: 'Yes, this tool is 100% free with no registration, no subscription, and no usage caps.',
      },
    ],
  },

  chatgpt: {
    id: 'chatgpt-ai-text-watermark-remover',
    name: 'ChatGPT AI Text Watermark Remover',
    provider: 'chatgpt',
    route: '/chatgpt-ai-text-watermark-remover',
    pageTitle: 'ChatGPT AI Text Watermark Remover – Free ChatGPT Text Cleaner',
    metaDescription: 'Scan, detect invisible characters, and clean ChatGPT-generated text with our free ChatGPT text watermark remover and cleaner.',
    h1: 'ChatGPT AI Text Watermark Remover',
    heroBadge: 'Specialized OpenAI ChatGPT Text Cleaner',
    leadParagraph: 'Analyze and clean ChatGPT-generated text for invisible characters, formatting artifacts, unusual whitespace, and other detectable text artifacts.',
    primaryKeywords: [
      'ChatGPT ai text watermark remover',
      'ChatGPT text watermark remover',
    ],
    secondaryKeywords: [
      'ChatGPT watermark remover',
      'ChatGPT AI watermark remover',
      'remove ChatGPT watermark',
      'ChatGPT text cleaner',
      'ChatGPT AI text cleaner',
      'clean ChatGPT text',
    ],
    features: [
      {
        title: 'Zero-Width Character Removal',
        description: 'Detects and strips zero-width spaces, word joiners, and BOM markers from ChatGPT copy-paste snippets.',
        iconName: 'Layers',
      },
      {
        title: 'NBSP & Space Normalization',
        description: 'Replaces sticky non-breaking spaces (U+00A0) and irregular tabulations with clean standard spaces.',
        iconName: 'FileCode',
      },
      {
        title: 'Unicode & Emoji Safe',
        description: 'Preserves all international language characters (Arabic, Urdu, Chinese, Japanese) and modern emojis.',
        iconName: 'ShieldCheck',
      },
      {
        title: 'Zero Account Required',
        description: 'Instant browser-side analysis with zero registration, zero credit limits, and full privacy.',
        iconName: 'Sparkles',
      },
    ],
    detectionCapabilities: [
      {
        title: 'Invisible Characters & Code Points',
        items: [
          'Zero Width Space (U+200B)',
          'Zero Width Non-Joiner (U+200C)',
          'Zero Width Joiner (U+200D)',
          'Zero Width No-Break Space (U+FEFF)',
          'Soft Hyphens (U+00AD)',
          'Control characters (U+0000 - U+001F)',
        ],
      },
      {
        title: 'ChatGPT Copy-Paste Formatting Issues',
        items: [
          'Non-Breaking Spaces (U+00A0)',
          'Mathematical & Ideographic Spaces (U+3000)',
          'Trailing formatting characters',
          'Triple space and inconsistent indentations',
          'Fragmented markdown code fence remnants',
        ],
      },
    ],
    faqs: [
      {
        question: 'What is a ChatGPT AI text watermark remover?',
        answer: 'A ChatGPT AI text watermark remover is a browser utility designed to inspect and clean text generated by OpenAI ChatGPT. It identifies hidden Unicode characters, zero-width spaces, and formatting artifacts introduced during web generation and clipboard copying.',
      },
      {
        question: 'Can this tool detect invisible characters in ChatGPT text?',
        answer: 'Yes. It thoroughly inspects every character code point to detect invisible formatting characters such as U+200B (Zero Width Space), U+FEFF (BOM), and U+00A0 (Non-Breaking Space).',
      },
      {
        question: 'How does ChatGPT text cleaning work?',
        answer: 'The cleaning engine filters out explicitly cataloged invisible and problematic characters while preserving all legitimate grammatical tokens, words, paragraphs, and multilingual characters.',
      },
      {
        question: 'Does this guarantee AI detector bypass?',
        answer: 'No. We are committed to technical honesty: removing invisible characters and cleaning formatting improves text hygiene and removes clipboard artifacts, but does not guarantee bypassing probabilistic AI content classifiers.',
      },
      {
        question: 'Is ChatGPT text cleaning free?',
        answer: 'Yes. The ChatGPT text cleaner is completely free to use without requiring any sign-up or credits.',
      },
      {
        question: 'Is my text stored?',
        answer: 'No. All cleaning operations are executed locally within your web browser. We do not store or transmit your submitted text.',
      },
    ],
  },

  general: {
    id: 'ai-text-watermark-remover',
    name: 'AI Text Watermark Remover',
    provider: 'general',
    route: '/ai-text-watermark-remover',
    pageTitle: 'AI Text Watermark Remover & Cleaner – Free Online Text Utility',
    metaDescription: 'Free online AI text watermark remover and cleaner. Detect invisible Unicode characters, formatting artifacts, and clean text locally.',
    h1: 'AI Text Watermark Remover & Cleaner',
    heroBadge: 'Universal AI Text Cleaner & Analyzer',
    leadParagraph: 'Analyze, detect invisible Unicode characters, formatting artifacts, and normalize AI-generated text with our free client-side tool.',
    primaryKeywords: [
      'AI text watermark remover',
      'AI text watermark cleaner',
    ],
    secondaryKeywords: [
      'remove AI watermark',
      'invisible character remover',
      'clean AI text',
      'AI text analyzer',
    ],
    features: [
      {
        title: 'Comprehensive Text Inspection',
        description: 'Scans text character-by-character for zero-width glyphs, byte order marks, and irregular spaces.',
        iconName: 'Search',
      },
      {
        title: 'Deterministic Cleaning',
        description: 'Strips only verified unwanted artifacts without mangling legitimate vocabulary or Unicode alphabets.',
        iconName: 'Eraser',
      },
      {
        title: 'Side-by-Side Comparison',
        description: 'Compare original and cleaned text with character count differences and removed artifact metrics.',
        iconName: 'Layers',
      },
      {
        title: 'Full Client-Side Privacy',
        description: 'Your text is never sent to external servers or stored in any database.',
        iconName: 'ShieldCheck',
      },
    ],
    detectionCapabilities: [
      {
        title: 'Hidden Unicode Artifacts',
        items: [
          'Zero Width Space (U+200B)',
          'Zero Width Joiner (U+200D)',
          'Byte Order Mark (U+FEFF)',
          'Word Joiner (U+2060)',
        ],
      },
      {
        title: 'Whitespace Anomalies',
        items: [
          'Non-Breaking Spaces (U+00A0)',
          'Thin Space (U+2009)',
          'Hair Space (U+200A)',
          'Double space clusters',
        ],
      },
    ],
    faqs: [
      {
        question: 'What does the AI text watermark remover do?',
        answer: 'It scans your text for hidden characters, zero-width markers, non-standard whitespace, and formatting artifacts, providing a clean and normalized plain text output.',
      },
      {
        question: 'Is this tool free?',
        answer: 'Yes, it is 100% free with no limits, no login, and no subscription.',
      },
      {
        question: 'Does it support multiple languages?',
        answer: 'Yes, all global Unicode writing systems including Arabic, Chinese, Japanese, Cyrillic, and emojis are fully supported and protected.',
      },
    ],
  },

  cleaner: {
    id: 'ai-text-cleaner',
    name: 'AI Text Cleaner',
    provider: 'general',
    route: '/ai-text-cleaner',
    pageTitle: 'AI Text Cleaner – Clean Formatting Artifacts & Whitespace Online',
    metaDescription: 'Free online AI text cleaner. Remove formatting artifacts, fix irregular spaces, and clean copied AI text.',
    h1: 'AI Text Cleaner',
    heroBadge: 'Fast Formatting & Whitespace Normalizer',
    leadParagraph: 'Clean formatting artifacts, irregular non-breaking spaces, and copy-paste remnants from AI-generated prose in seconds.',
    primaryKeywords: [
      'AI text cleaner',
      'clean AI text',
    ],
    secondaryKeywords: [
      'format cleaner',
      'whitespace cleaner',
      'text normalizer',
    ],
    features: [
      {
        title: 'Whitespace Cleanup',
        description: 'Normalizes non-breaking spaces, excessive tabulations, and irregular line breaks.',
        iconName: 'FileCode',
      },
      {
        title: 'Symbol Sanitization',
        description: 'Cleans rogue markdown delimiters, orphaned bullet points, and stray control symbols.',
        iconName: 'Eraser',
      },
      {
        title: 'Grammar Preservation',
        description: 'Ensures sentence capitalization, standard punctuation, and paragraph breaks are preserved.',
        iconName: 'ShieldCheck',
      },
      {
        title: 'One-Click Copy & Export',
        description: 'Instantly copy cleaned text to clipboard or download as a .txt file.',
        iconName: 'Download',
      },
    ],
    detectionCapabilities: [
      {
        title: 'Formatting Elements Cleaned',
        items: [
          'Multiple continuous space sequences',
          'Sticky non-breaking space (NBSP) characters',
          'Orphaned markdown symbols and code tags',
          'Excessive trailing carriage returns',
        ],
      },
    ],
    faqs: [
      {
        question: 'How does the AI text cleaner work?',
        answer: 'It applies deterministic rules to normalize whitespace and remove formatting artifacts from copied text while keeping content and meaning intact.',
      },
      {
        question: 'Will it alter my vocabulary or words?',
        answer: 'No. The cleaner only removes invisible artifacts and abnormal whitespace without altering your chosen words.',
      },
    ],
  },

  invisible: {
    id: 'invisible-character-remover',
    name: 'Invisible Character Remover',
    provider: 'invisible',
    route: '/invisible-character-remover',
    pageTitle: 'Invisible Character Remover – Detect & Remove Zero-Width Unicode',
    metaDescription: 'Detect and remove invisible Unicode characters, zero-width spaces, BOM, and hidden text markers online for free.',
    h1: 'Invisible Character Remover',
    heroBadge: 'Zero-Width & Unicode Control Character Scanner',
    leadParagraph: 'Scan, detect, and eliminate hidden zero-width characters, byte order marks, and invisible Unicode control markers.',
    primaryKeywords: [
      'invisible character remover',
      'remove invisible characters',
    ],
    secondaryKeywords: [
      'zero width space remover',
      'BOM remover',
      'unicode cleaner',
      'hidden character detector',
    ],
    features: [
      {
        title: 'Deep Zero-Width Scan',
        description: 'Exposes U+200B (ZWSP), U+200C (ZWNJ), U+200D (ZWJ), and U+2060 (Word Joiner) code points.',
        iconName: 'Search',
      },
      {
        title: 'Detailed Position Mapping',
        description: 'Identifies exact character counts and occurrences of invisible elements inside your string.',
        iconName: 'Layers',
      },
      {
        title: 'Surgical Removal',
        description: 'Safely removes hidden markers while preserving emojis and proper foreign language ligatures.',
        iconName: 'ShieldCheck',
      },
      {
        title: 'Export & Copy',
        description: 'Copy sanitized text instantly to your clipboard or download as a clean plain text file.',
        iconName: 'Download',
      },
    ],
    detectionCapabilities: [
      {
        title: 'Detected Invisible Unicode Characters',
        items: [
          'U+200B : Zero Width Space',
          'U+200C : Zero Width Non-Joiner',
          'U+200D : Zero Width Joiner',
          'U+2060 : Word Joiner',
          'U+FEFF : Zero Width No-Break Space (BOM)',
          'U+00AD : Soft Hyphen',
        ],
      },
    ],
    faqs: [
      {
        question: 'Why do invisible characters appear in my text?',
        answer: 'Web editors and rich text formatting systems often use invisible characters for cursor anchoring, line-break prevention, and script joining. When copying text, these characters transfer unnoticed into your clipboard.',
      },
      {
        question: 'Can invisible characters cause problems?',
        answer: 'Yes. They can cause database indexing bugs, search mismatches, code parsing errors, and trigger automated anomaly detection scripts.',
      },
    ],
  },
};
